service: node-serverless-app
frameworkVersion: '3'

custom:
  tableName: 'todos-table-${sls:stage}'

provider:
  name: aws
  runtime: nodejs14.x
  profile: serverless-admin
  memorySize: 128
  timeout: 10
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [ TodosTable, Arn ]
  environment:
    TODO_TABLE: ${self:custom.tableName}

functions:
  create:
    handler: app/createTodo.createTodo
    events:
      - http:
          path: todos
          method: post
          cors: true

  list:
    handler: app/listTodos.listTodos
    events:
      - http:
          path: todos
          method: get
          cors: true

  find:
    handler: app/findTodo.findTodo
    events:
      - http:
          path: todos/{id}
          method: get
          cors: true

  delete:
    handler: app/deleteTodo.deleteTodo
    events:
      - http:
          path: todos/{id}
          method: delete
          cors: true

resources:
  Resources:
    TodosTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.tableName}

plugins:
  - serverless-plugin-typescript
  - serverless-offline